[time]
disabled = false
style = "dimmed bold yellow"

[python]
python_binary = ["python"]
symbol = ' '

[conda]
ignore_base = false

[aws]
symbol = ' '

[gcloud]
symbol = '󰊭 '
detect_env_vars = [
    "GOOGLE_APPLICATION_CREDENTIALS",
    "GCLOUD_CONFIG",
]
format = 'on $symbol$active '

[azure]
symbol = ' '
